---
minimalCharacteristicLength: 0.05 #minimal L_c in [m]
simulationType: COLLISION         #COLLISION or EXPLOSION
currentMaxID: 48514               #Derived from satcat.csv
inputSource: ["../data.yaml"]     #Alternative: ["../satcat.csv", "../tle.txt"]