---
simulation:
  minimalCharacteristicLength: 0.05           #minimal L_c in [m]
  simulationType: COLLISION                   #COLLISION or EXPLOSION
  currentMaxID: 48514                         #Derived from satcat.csv
  inputSource: ["../data.yaml"]               #Alternative: ["../satcat.csv", "../tle.txt"]
  #idFilter: [123, 456]                       #Optional: IDs of satellites to use (two for collision, one for explosion)
inputOutput:
  target: ["input.csv", "input.vtu"]
  #kepler: True
  #csvPattern: "IL"
resultOutput:
  target: ["result.csv", "result.vtu"]
  #kepler: True
  #csvPattern: "IL"