---
#Data taken from Liou, J.-C., et al. “The new NASA orbital debris breakup model” COSPAR Colloquia Series Volume 15 (2002): 363-367
simulation:
  minimalCharacteristicLength: 0.1
  simulationType: EXPLOSION
  inputSource: ["../data_nimbus6.yaml"]
inputOutput:
  target: ["nimbus6_input.csv", "nimbus6_input.vtu"]
resultOutput:
  target: ["nimbus6_result.csv", "nimbus6_result.vtu"]