---
simulation:
  minimalCharacteristicLength: 0.05
  inputSource: ["../example-config/satcat.csv", "../example-config/cosmos-2251-debris.txt"]
inputOutput:
  target: ["cosmos_fragments.csv"]
  kepler: True