---
#Data taken from Liou, J.-C., et al. “The new NASA orbital debris breakup model” COSPAR Colloquia Series Volume 15 (2002): 363-367
#The full-tle.txt file contains TLE data for every satcat catalog, it can be obtained on https://www.space-track.org/
simulation:
  minimalCharacteristicLength: 0.1
  simulationType: EXPLOSION
  inputSource: ["../example-config/satcat.csv", "../example-config/full-tle.txt"]
  idFilter: [10702]
inputOutput:
  target: ["landsat3_input.csv"]
resultOutput:
  target: ["landsat3_result.csv"]